// SPDX-FileCopyrightText: 2026 Zakaria Fatahi and Hifz Companion contributors
// SPDX-License-Identifier: GPL-3.0-or-later

import 'package:flutter/foundation.dart';
import 'package:models/models.dart';

import 'pack_coordinates.dart';
import 'pinned_manifest_data.dart';

/// One pinned asset in a pack: its [name], expected [sha256] (lower-case hex),
/// byte size [bytes], and — so a single CI run proves the muṣḥaf is
/// simultaneously *intact* (R1) and *lawfully redistributed* (R2) — its
/// [source] and [license]. The [source]/[license] back the in-app attribution
/// surface (E05-T09). Never widened toward parsing attestation/Sigstore data
/// (that is CI/audit only; engineering 09 §4).
@immutable
class ManifestEntry {
  /// Creates a manifest entry.
  const ManifestEntry({
    required this.name,
    required this.sha256,
    required this.bytes,
    required this.source,
    required this.license,
  });

  /// The asset file name (e.g. `'quran-uthmani.db'`, `'QCF_P001.ttf'`).
  final String name;

  /// The expected SHA-256, lower-case hex. Empty until E05-T10 pins it from the
  /// bundled asset — an empty digest never matches real bytes, so an unpinned
  /// entry fails verification **closed**.
  final String sha256;

  /// The asset's byte length (`0` until pinned by E05-T10).
  final int bytes;

  /// Where the asset came from (e.g. `'tanzil.net'`, `'qul.tarteel.ai'`,
  /// `'kfgqpc'`, `'repo'`) — the lawful-redistribution / attribution surface.
  final String source;

  /// The asset's licence (e.g. `'verbatim+attribution'`, `'QUL'`, `'KFGQPC'`).
  final String license;

  @override
  bool operator ==(Object other) =>
      other is ManifestEntry &&
      other.name == name &&
      other.sha256 == sha256 &&
      other.bytes == bytes &&
      other.source == source &&
      other.license == license;

  @override
  int get hashCode => Object.hash(name, sha256, bytes, source, license);
}

/// The pinned manifest for one pack: the [pack] kind, the [tag] it was built
/// from, the [mushafId] it describes, and one [ManifestEntry] per file in
/// [files].
///
/// **Bundle-first (amended 2026-06-18):** for the core pack this manifest is the
/// **build-time** trust channel over the *bundled* assets — baked into the
/// signed binary, never read from a sidecar `SHA256SUMS` file. [tag] records the
/// bundled edition's version; it is not a runtime download pointer (the core is
/// bundled, not fetched).
@immutable
class CorePackManifest {
  /// Creates a pinned pack manifest.
  const CorePackManifest({
    required this.pack,
    required this.tag,
    required this.mushafId,
    required this.files,
  });

  /// The pack kind (`'core'`).
  final String pack;

  /// The exact tag the assets were built from (e.g. `'core-v1.0.0'`).
  final String tag;

  /// The muṣḥaf edition id this manifest describes (matches the
  /// `MushafEdition.mushafId` it is built from).
  final String mushafId;

  /// Every pinned file, in a fixed order: text, layout, mutashābihāt, then one
  /// entry per page font (`1..pageCount`).
  final List<ManifestEntry> files;
}

/// The pinned manifest **baked into the signed binary** — the independent trust
/// channel the verifier (E05-T03) compares against, and that the build-time gate
/// (E05-T10) re-derives from the bundled assets.
///
/// [core] is built from the default bundled edition (`kKfgqpcHafsMadaniV2Edition`),
/// so its [CorePackManifest.mushafId] and font count cannot drift from the
/// edition. The digest/byte *values* come from `pinned_manifest_data.dart`,
/// generated by `tool/gen_core_manifest.dart` against the bundled assets (empty
/// placeholders until E05-T10 pins them).
abstract final class EmbeddedManifest {
  /// The pinned core-pack manifest for the default bundled edition.
  static final CorePackManifest core = buildCoreManifest(
    kKfgqpcHafsMadaniV2Edition,
  );

  /// The file name of the bundled text asset (Tanzil Uthmani).
  static const String textFileName = 'quran-uthmani.db';

  /// The file name of the bundled QUL page-layout asset.
  static const String layoutFileName = 'layout-qul.json';

  /// The file name of the bundled mutashābihāt dataset.
  static const String mutashabihatFileName = 'mutashabihat.json';

  /// The font file name for [page] (`'QCF_P001.ttf'` … `'QCF_P604.ttf'`).
  static String fontFileName(int page) =>
      'QCF_P${page.toString().padLeft(3, '0')}.ttf';
}

/// Builds the pinned manifest for [edition]: the text, layout, and mutashābihāt
/// entries followed by one font entry per page (`1..edition.pageCount`), with
/// digests/byte sizes from the generated `pinned_manifest_data.dart` (empty
/// until pinned). Public so a wrong-edition swap is testable.
CorePackManifest buildCoreManifest(MushafEdition edition) {
  final files = <ManifestEntry>[
    const ManifestEntry(
      name: EmbeddedManifest.textFileName,
      sha256: kCoreTextSha256,
      bytes: kCoreTextBytes,
      source: 'tanzil.net',
      license: 'verbatim+attribution',
    ),
    const ManifestEntry(
      name: EmbeddedManifest.layoutFileName,
      sha256: kCoreLayoutSha256,
      bytes: kCoreLayoutBytes,
      source: 'qul.tarteel.ai',
      license: 'QUL',
    ),
    const ManifestEntry(
      name: EmbeddedManifest.mutashabihatFileName,
      sha256: kCoreMutashabihatSha256,
      bytes: kCoreMutashabihatBytes,
      source: 'repo',
      license: 'CC-BY (scholar-reviewed)',
    ),
    for (var page = 1; page <= edition.pageCount; page++)
      ManifestEntry(
        name: EmbeddedManifest.fontFileName(page),
        sha256: kCorePageFontSha256[page] ?? '',
        bytes: kCorePageFontBytes[page] ?? 0,
        source: 'kfgqpc',
        license: 'KFGQPC',
      ),
  ];
  return CorePackManifest(
    pack: 'core',
    tag: PackCoordinates.pinnedTag,
    mushafId: edition.mushafId,
    files: List<ManifestEntry>.unmodifiable(files),
  );
}
