// SPDX-FileCopyrightText: 2026 Zakaria Fatahi and Hifz Companion contributors
// SPDX-License-Identifier: GPL-3.0-or-later

// GENERATED by tool/gen_core_manifest.dart — do NOT edit by hand.
// Regenerate against the bundled assets:
//   dart run tool/gen_core_manifest.dart --assets-dir <dir>
//
// The digest/byte values the binary-baked core manifest reads. Empty
// placeholders (digest '', bytes 0) until E05-T10 pins them from the
// real bundled assets; an empty digest never matches real bytes, so an
// unpinned asset fails verification CLOSED.

/// SHA-256 of the bundled Tanzil text asset.
const String kCoreTextSha256 = '';

/// Byte length of the bundled Tanzil text asset.
const int kCoreTextBytes = 0;

/// SHA-256 of the bundled QUL page-layout asset.
const String kCoreLayoutSha256 = '';

/// Byte length of the bundled QUL page-layout asset.
const int kCoreLayoutBytes = 0;

/// SHA-256 of the bundled mutashābihāt dataset.
const String kCoreMutashabihatSha256 = '';

/// Byte length of the bundled mutashābihāt dataset.
const int kCoreMutashabihatBytes = 0;

/// Page → its bundled glyph-font SHA-256 (lower-case hex). Entries are
/// present only for pinned pages; a missing page reads as the empty
/// (unpinned) digest in the manifest builder.
const Map<int, String> kCorePageFontSha256 = <int, String>{};

/// Page → its bundled glyph-font byte length.
const Map<int, int> kCorePageFontBytes = <int, int>{};
