// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    mushaf,
    profile,
    surah,
    page,
    card,
    lineBlock,
    reviewLog,
    ayah,
    confusionEdge,
    cycleConfig,
    appMeta,
    line,
    mutashabihGroup,
    mutashabihMember,
    cardDue,
    lineBlockByCard,
    reviewLogByCard,
    lineByPage,
    ayahByPage,
  ];
  late final Shape0 mushaf = Shape0(
      source: i0.VersionedTable(
        entityName: 'mushaf',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(mushaf_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 profile = Shape1(
      source: i0.VersionedTable(
        entityName: 'profile',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(profile_id)',
          'CHECK(role IN (\'self\', \'student\', \'child\'))',
          'CHECK(locale IN (\'ar\', \'fa\', \'ckb\'))',
        ],
        columns: [
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 surah = Shape2(
      source: i0.VersionedTable(
        entityName: 'surah',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(surah_id)',
          'CHECK(surah_id BETWEEN 1 AND 114)',
          'CHECK(revelation IN (\'meccan\', \'medinan\'))',
          'CHECK(ayah_count > 0)',
        ],
        columns: [
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 page = Shape3(
      source: i0.VersionedTable(
        entityName: 'page',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(page_id)',
          'CHECK(page_id BETWEEN 1 AND 604)',
          'CHECK(juz BETWEEN 1 AND 30)',
          'CHECK(hizb BETWEEN 1 AND 60)',
          'CHECK(rub BETWEEN 1 AND 240)',
        ],
        columns: [
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_3,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 card = Shape4(
      source: i0.VersionedTable(
        entityName: 'card',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(profile_id, page_id)',
          'CHECK(track IN (\'NEW\', \'NEAR\', \'FAR\', \'UNMEMORIZED\'))',
          'CHECK(d BETWEEN 1 AND 10)',
          'CHECK(s >= 0)',
          'CHECK(reps >= 0)',
          'CHECK(lapses >= 0)',
          'CHECK(signoffs >= 0)',
          'CHECK(track = \'UNMEMORIZED\' OR due_at IS NOT NULL)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 lineBlock = Shape5(
      source: i0.VersionedTable(
        entityName: 'line_block',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(block_id)',
          'CHECK(line_start BETWEEN 1 AND 15)',
          'CHECK(line_end BETWEEN line_start AND 15)',
          'CHECK(error_count >= 0)',
        ],
        columns: [
          _column_42,
          _column_28,
          _column_29,
          _column_43,
          _column_44,
          _column_45,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 reviewLog = Shape6(
      source: i0.VersionedTable(
        entityName: 'review_log',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(log_id)',
          'CHECK(track_at_review IN (\'NEW\', \'NEAR\', \'FAR\', \'UNMEMORIZED\'))',
          'CHECK(grade IN (\'again\', \'hard\', \'good\', \'easy\'))',
          'CHECK(source IN (\'self\', \'teacher\'))',
        ],
        columns: [
          _column_46,
          _column_28,
          _column_29,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 ayah = Shape7(
      source: i0.VersionedTable(
        entityName: 'ayah',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(ayah_id)',
        ],
        columns: [
          _column_59,
          _column_60,
          _column_61,
          _column_29,
          _column_62,
          _column_63,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 confusionEdge = Shape8(
      source: i0.VersionedTable(
        entityName: 'confusion_edge',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(profile_id, ayah_a, ayah_b)',
          'CHECK(ayah_a < ayah_b)',
        ],
        columns: [
          _column_28,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 cycleConfig = Shape9(
      source: i0.VersionedTable(
        entityName: 'cycle_config',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(profile_id)',
          'CHECK(new_lines_per_day >= 0)',
          'CHECK(near_window_juz >= 0)',
          'CHECK(far_target_per_day >= 0)',
          'CHECK(far_cycle_days > 0)',
          'CHECK(daily_budget_minutes > 0)',
        ],
        columns: [
          _column_28,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 appMeta = Shape10(
      source: i0.VersionedTable(
        entityName: 'app_meta',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY("key")',
        ],
        columns: [
          _column_77,
          _column_78,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 line = Shape11(
      source: i0.VersionedTable(
        entityName: 'line',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(line_id)',
          'CHECK(line_no BETWEEN 1 AND 15)',
          'CHECK(line_type IN (\'ayah\', \'surah_header\', \'basmala\'))',
        ],
        columns: [
          _column_79,
          _column_29,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 mutashabihGroup = Shape12(
      source: i0.VersionedTable(
        entityName: 'mutashabih_group',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(group_id)',
          'CHECK(type IN (\'identical\', \'near_identical\', \'structural\'))',
        ],
        columns: [
          _column_84,
          _column_85,
          _column_86,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 mutashabihMember = Shape13(
      source: i0.VersionedTable(
        entityName: 'mutashabih_member',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [
          'PRIMARY KEY(group_id, ayah_id)',
        ],
        columns: [
          _column_87,
          _column_88,
          _column_89,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index cardDue = i1.Index(
      'card_due', 'CREATE INDEX card_due ON card (profile_id, track, due_at)');
  final i1.Index lineBlockByCard = i1.Index('line_block_by_card',
      'CREATE INDEX line_block_by_card ON line_block (profile_id, page_id)');
  final i1.Index reviewLogByCard = i1.Index('review_log_by_card',
      'CREATE INDEX review_log_by_card ON review_log (profile_id, page_id, reviewed_at)');
  final i1.Index lineByPage = i1.Index(
      'line_by_page', 'CREATE INDEX line_by_page ON line (page_id, line_no)');
  final i1.Index ayahByPage =
      i1.Index('ayah_by_page', 'CREATE INDEX ayah_by_page ON ayah (page_id)');
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get mushafId =>
      columnsByName['mushaf_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get riwayah =>
      columnsByName['riwayah']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lineCount =>
      columnsByName['line_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pageCount =>
      columnsByName['page_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fontFamily =>
      columnsByName['font_family']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checksumSha256 =>
      columnsByName['checksum_sha256']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('mushaf_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('riwayah', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>('line_count', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>('page_count', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('font_family', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('checksum_sha256', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mushafId =>
      columnsByName['mushaf_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get settingsJson =>
      columnsByName['settings_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('profile_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('display_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>('role', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>('locale', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('mushaf_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL REFERENCES mushaf(mushaf_id)');
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('created_at', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('settings_json', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get surahId =>
      columnsByName['surah_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nameAr =>
      columnsByName['name_ar']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revelation =>
      columnsByName['revelation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ayahCount =>
      columnsByName['ayah_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bismillahPre =>
      columnsByName['bismillah_pre']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('surah_id', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('name_ar', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('revelation', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('ayah_count', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('bismillah_pre', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL CHECK (bismillah_pre IN (0, 1))');

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get juz =>
      columnsByName['juz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hizb =>
      columnsByName['hizb']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rub =>
      columnsByName['rub']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get surahStart =>
      columnsByName['surah_start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ayahStart =>
      columnsByName['ayah_start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get surahEnd =>
      columnsByName['surah_end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ayahEnd =>
      columnsByName['ayah_end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineCount =>
      columnsByName['line_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qpcFontName =>
      columnsByName['qpc_font_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('page_id', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('juz', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>('hizb', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('rub', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>('surah_start', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>('ayah_start', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>('surah_end', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>('ayah_end', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>('qpc_font_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get track =>
      columnsByName['track']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get d =>
      columnsByName['d']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get s =>
      columnsByName['s']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get lastReviewAt =>
      columnsByName['last_review_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reps =>
      columnsByName['reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lapses =>
      columnsByName['lapses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weakFlag =>
      columnsByName['weak_flag']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get signoffs =>
      columnsByName['signoffs']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get manualLock =>
      columnsByName['manual_lock']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get prayerCritical =>
      columnsByName['prayer_critical']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('profile_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints:
            'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('page_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES page(page_id)');
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('track', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>('d', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>('s', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>('last_review_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>('due_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>('reps', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>('lapses', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>('weak_flag', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (weak_flag IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>('signoffs', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>('manual_lock', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (manual_lock IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>('prayer_critical', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 0 CHECK (prayer_critical IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>('enabled', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get blockId =>
      columnsByName['block_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineStart =>
      columnsByName['line_start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineEnd =>
      columnsByName['line_end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get errorCount =>
      columnsByName['error_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>('block_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('line_start', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>('line_end', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>('error_count', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reviewedAt =>
      columnsByName['reviewed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackAtReview =>
      columnsByName['track_at_review']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get errorLinesJson =>
      columnsByName['error_lines_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get elapsedDays =>
      columnsByName['elapsed_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get rPredicted =>
      columnsByName['r_predicted']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sBefore =>
      columnsByName['s_before']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sAfter =>
      columnsByName['s_after']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get dBefore =>
      columnsByName['d_before']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get dAfter =>
      columnsByName['d_after']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get teacherLabel =>
      columnsByName['teacher_label']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>('log_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>('reviewed_at', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>('track_at_review', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>('grade', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>('error_lines_json', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>('elapsed_days', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_52(String aliasedName) =>
    i1.GeneratedColumn<double>('r_predicted', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_53(String aliasedName) =>
    i1.GeneratedColumn<double>('s_before', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>('s_after', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_55(String aliasedName) =>
    i1.GeneratedColumn<double>('d_before', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>('d_after', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>('source', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>('teacher_label', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ayahId =>
      columnsByName['ayah_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get surah =>
      columnsByName['surah']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ayah =>
      columnsByName['ayah']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lineRefsJson =>
      columnsByName['line_refs_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sajda =>
      columnsByName['sajda']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>('ayah_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>('surah', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>('ayah', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>('line_refs_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>('sajda', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL CHECK (sajda IN (0, 1))');

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ayahA =>
      columnsByName['ayah_a']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ayahB =>
      columnsByName['ayah_b']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get lastConfusedAt =>
      columnsByName['last_confused_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>('ayah_a', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>('ayah_b', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>('weight', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>('last_confused_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cycleType =>
      columnsByName['cycle_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get newLinesPerDay =>
      columnsByName['new_lines_per_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nearWindowJuz =>
      columnsByName['near_window_juz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get farTargetPerDay =>
      columnsByName['far_target_per_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get farCycleDays =>
      columnsByName['far_cycle_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyBudgetMinutes =>
      columnsByName['daily_budget_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pureCycleMode =>
      columnsByName['pure_cycle_mode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get termLabelSet =>
      columnsByName['term_label_set']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get regionPreset =>
      columnsByName['region_preset']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>('cycle_type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>('new_lines_per_day', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>('near_window_juz', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>('far_target_per_day', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>('far_cycle_days', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>('daily_budget_minutes', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>('pure_cycle_mode', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 0 CHECK (pure_cycle_mode IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>('term_label_set', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>('region_preset', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>('key', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>('value', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get lineId =>
      columnsByName['line_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lineNo =>
      columnsByName['line_no']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lineType =>
      columnsByName['line_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ayahRefsJson =>
      columnsByName['ayah_refs_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get textGlyphRef =>
      columnsByName['text_glyph_ref']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>('line_id', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_80(String aliasedName) =>
    i1.GeneratedColumn<int>('line_no', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>('line_type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>('ayah_refs_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>('text_glyph_ref', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get noteKey =>
      columnsByName['note_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>('group_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>('note_key', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ayahId =>
      columnsByName['ayah_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distinguishingWordIndexJson =>
      columnsByName['distinguishing_word_index_json']!
          as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>('group_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL REFERENCES mutashabih_group(group_id)');
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>('ayah_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
        'distinguishing_word_index_json', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
    ));
