// SPDX-FileCopyrightText: 2026 Zakaria Fatahi and Hifz Companion contributors
// SPDX-License-Identifier: GPL-3.0-or-later

// Build helper for the pinned core-pack manifest data.
//
// Emits `packages/assets/lib/src/pinned_manifest_data.dart` — the digest/byte
// *values* the binary-baked manifest (`pinned_manifest.dart`) reads. Keeping
// the 604 per-page font entries generated (not 604 hand-written lines) makes
// the manifest auditable: re-run this against the bundled assets and diff.
//
// Bundle-first (amended 2026-06-18): the core muṣḥaf is bundled in the binary,
// so this hashes the *bundled* asset files. With no `--assets-dir` it emits
// empty placeholders (digests `''`, bytes `0`) so the structure compiles before
// the real ~40–55 MB asset set is sourced; E05-T10 runs it against the real
// bundled assets to pin every hash.
//
// Usage:
//   dart run tool/gen_core_manifest.dart [--assets-dir <dir>] [--page-count 604]
//
// Expected file names under <assets-dir>: quran-uthmani.db, layout-qul.json,
// mutashabihat.json, and QCF_P001.ttf … QCF_P{pageCount}.ttf.

import 'dart:io';

import 'package:crypto/crypto.dart';

const String _outputPath = 'packages/assets/lib/src/pinned_manifest_data.dart';
const String _textFile = 'quran-uthmani.db';
const String _layoutFile = 'layout-qul.json';
const String _mutashabihatFile = 'mutashabihat.json';

String _fontFile(int page) => 'QCF_P${page.toString().padLeft(3, '0')}.ttf';

void main(List<String> args) {
  final assetsDir = _argValue(args, '--assets-dir');
  final pageCount = int.parse(_argValue(args, '--page-count') ?? '604');

  ({String sha256, int bytes}) digest(String name) {
    if (assetsDir == null) return (sha256: '', bytes: 0);
    final file = File('$assetsDir/$name');
    if (!file.existsSync()) {
      stderr.writeln('  ! missing bundled asset: $name (left as placeholder)');
      return (sha256: '', bytes: 0);
    }
    final bytes = file.readAsBytesSync();
    return (sha256: sha256.convert(bytes).toString(), bytes: bytes.length);
  }

  final text = digest(_textFile);
  final layout = digest(_layoutFile);
  final mutashabihat = digest(_mutashabihatFile);

  final fontSha = <int, String>{};
  final fontBytes = <int, int>{};
  for (var page = 1; page <= pageCount; page++) {
    final d = digest(_fontFile(page));
    if (d.sha256.isNotEmpty) {
      fontSha[page] = d.sha256;
      fontBytes[page] = d.bytes;
    }
  }

  // REUSE-IgnoreStart — these strings EMIT the generated file's SPDX header;
  // they are not this file's own license tag (which is at the top).
  final buffer = StringBuffer()
    ..writeln('// SPDX-FileCopyrightText: 2026 Zakaria Fatahi and Hifz '
        'Companion contributors')
    ..writeln('// SPDX-License-Identifier: GPL-3.0-or-later')
    // REUSE-IgnoreEnd
    ..writeln()
    ..writeln('// GENERATED by tool/gen_core_manifest.dart — do NOT edit by '
        'hand.')
    ..writeln('// Regenerate against the bundled assets:')
    ..writeln('//   dart run tool/gen_core_manifest.dart --assets-dir <dir>')
    ..writeln('//')
    ..writeln('// The digest/byte values the binary-baked core manifest reads. '
        'Empty')
    ..writeln('// placeholders (digest \'\', bytes 0) until E05-T10 pins them '
        'from the')
    ..writeln('// real bundled assets; an empty digest never matches real '
        'bytes, so an')
    ..writeln('// unpinned asset fails verification CLOSED.')
    ..writeln()
    ..writeln("/// SHA-256 of the bundled Tanzil text asset.")
    ..writeln("const String kCoreTextSha256 = '${text.sha256}';")
    ..writeln('/// Byte length of the bundled Tanzil text asset.')
    ..writeln('const int kCoreTextBytes = ${text.bytes};')
    ..writeln('/// SHA-256 of the bundled QUL page-layout asset.')
    ..writeln("const String kCoreLayoutSha256 = '${layout.sha256}';")
    ..writeln('/// Byte length of the bundled QUL page-layout asset.')
    ..writeln('const int kCoreLayoutBytes = ${layout.bytes};')
    ..writeln('/// SHA-256 of the bundled mutashābihāt dataset.')
    ..writeln("const String kCoreMutashabihatSha256 = "
        "'${mutashabihat.sha256}';")
    ..writeln('/// Byte length of the bundled mutashābihāt dataset.')
    ..writeln('const int kCoreMutashabihatBytes = ${mutashabihat.bytes};')
    ..writeln()
    ..writeln('/// Page → its bundled glyph-font SHA-256 (lower-case hex). '
        'Entries are')
    ..writeln('/// present only for pinned pages; a missing page reads as the '
        "empty")
    ..writeln('/// (unpinned) digest in the manifest builder.')
    ..writeln('const Map<int, String> kCorePageFontSha256 = '
        '${_intStringMapLiteral(fontSha)};')
    ..writeln('/// Page → its bundled glyph-font byte length.')
    ..writeln('const Map<int, int> kCorePageFontBytes = '
        '${_intIntMapLiteral(fontBytes)};');

  File(_outputPath).writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote $_outputPath '
      '(${fontSha.length}/$pageCount fonts pinned, '
      "text=${text.sha256.isEmpty ? 'placeholder' : 'pinned'}).");
}

String _intStringMapLiteral(Map<int, String> map) {
  if (map.isEmpty) return '<int, String>{}';
  final entries =
      map.entries.map((e) => "  ${e.key}: '${e.value}',").join('\n');
  return '<int, String>{\n$entries\n}';
}

String _intIntMapLiteral(Map<int, int> map) {
  if (map.isEmpty) return '<int, int>{}';
  final entries = map.entries.map((e) => '  ${e.key}: ${e.value},').join('\n');
  return '<int, int>{\n$entries\n}';
}

String? _argValue(List<String> args, String flag) {
  final index = args.indexOf(flag);
  if (index == -1 || index + 1 >= args.length) return null;
  return args[index + 1];
}
