// SPDX-License-Identifier: GPL-3.0-or-later
//
// SCAFFOLD — copy the relevant piece into the `/data` package, then fill every // TODO:.
// This file imports `drift` and is meaningful ONLY inside `packages/data/` — the single
// package allowed to see drift/sqlite3 (docs/engineering/05-persistence-and-encryption.md §1;
// the banned-import gate is owned by eng-create-package). Opening it on its own shows
// unresolved symbols (`HifzDatabase`, generated `_$HifzDatabase`, `CalendarDate`, the DAOs) —
// that is expected: it is a starting point, not a standalone file.
//
// FIVE pieces, all in `/data`:
//   1. A new STRICT user table class (CHECK / FK constraints, CalendarDate-serial day columns).
//   2. The @DriftDatabase schemaVersion bump + stepByStep migration + committed-snapshot workflow.
//   3. The connection setup/beforeOpen pragmas (WAL, synchronous=FULL, foreign_keys=ON)
//      + the opt-in PRAGMA cipher liveness guard.
//   4. The append-only DAO + the commitReview single-db.transaction repository body.
//   5. The v(n-1) migration fixture test with PRAGMA integrity_check (authored via eng-write-dart-test).
//
// Constraints live in the SCHEMA, not in Dart. Scheduling days are CalendarDate serial integers,
// never DateTime instants. review_log is append-only (no UPDATE/DELETE DAO). Reference tables are
// read-only by construction. Persist BEFORE you publish; await every query inside a transaction.
//
// Governing docs:
//   docs/engineering/05-persistence-and-encryption.md §1 (Drift in /data; setup pragmas),
//     §2 (STRICT schema, CHECK/FK, append-only review_log, CalendarDate days, no stored derived state),
//     §3 (one db.transaction per review, WAL+synchronous=FULL, persist-before-publish, the await footgun),
//     §4 (stepByStep migrations, committed snapshots, append-only, fixture test + integrity_check),
//     §5 (opt-in encryption, PRAGMA cipher guard, key lifecycle).
//   docs/engineering/11-testing-strategy.md §1, §8 (the migration fixture test tier + CI job).

import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

// CalendarDate is the project's serial-day value type (domain-calendars-and-hifzdate).
// A scheduling-day column stores its integer serial day — NEVER a DateTime instant.
// import 'package:models/models.dart' show CalendarDate; // TODO: real import.

part 'hifz_database.g.dart'; // generated by build_runner — drift codegen.

// =====================================================================================
// 1. A NEW STRICT USER TABLE
// -------------------------------------------------------------------------------------
// Encode every invariant in the table so a corrupt row is unrepresentable at the storage
// layer (§2). Enums => check(... isIn ...); ranges => check(...); referential integrity
// => references(...); the whole table => withoutRowId/STRICT discipline. Scheduling days
// are integer CalendarDate serial days; true event times are UTC ISO-8601 TEXT.
// =====================================================================================

// TODO: rename to the real table; this is an illustrative new per-profile user table.
class StudyNotes extends Table {
  // UUID primary key as TEXT (matches the §2 id convention).
  TextColumn get noteId => text()();

  // FK to the owning profile; per-profile children cascade on profile delete (§2).
  // TODO: point at the real Profiles table reference.
  TextColumn get profileId =>
      text().references(Profiles, #profileId, onDelete: KeyAction.cascade)();

  // FK into the read-only reference table — fine to REFERENCE a reference table,
  // never to WRITE one (§2: reference tables are read-only by construction).
  IntColumn get pageId => integer().references(Pages, #pageId)();

  // Enumerable column constrained with a CHECK (... IN (...)) — not validated in Dart (§2).
  // TODO: replace with the real domain enum's wire values.
  TextColumn get kind =>
      text().check(kind.isIn(const ['anchor', 'reminder', 'correction']))();

  // SCHEDULING DAY: a CalendarDate serial integer, NULL until first relevant.
  // NEVER a DateTime here — an instant column reintroduces the DST off-by-one (§2 pitfalls).
  IntColumn get dueAt => integer().nullable()();

  // A true event instant — stored UTC ISO-8601 TEXT (§2).
  TextColumn get createdAtUtc => text()();

  // Small, schema-shaped, decode-validated JSON only — never Quran text or health facts (§2).
  TextColumn get payloadJson => text().nullable()();

  @override
  Set<Column> get primaryKey => {noteId};

  // STRICT + extra table-level invariants. Mirror the engine invariant defended in §2:
  // a memorized card always has a due_at — here, an example range/null guard.
  @override
  List<String> get customConstraints => const [
        // TODO: tailor to the real table's invariants (kept in SQL, not Dart).
        'CHECK (due_at IS NULL OR due_at >= 0)',
      ];

  // STRICT tables: a column never silently coerces (§2). Drift emits STRICT when asked.
  @override
  bool get isStrict => true;
}

// =====================================================================================
// 2. THE @DriftDatabase: schemaVersion BUMP + stepByStep MIGRATION
// -------------------------------------------------------------------------------------
// Migrations are guided + append-only (§4). To ship this table:
//   (a) add it to `tables:` below and bump `schemaVersion`;
//   (b) `dart run drift_dev schema dump` -> commit the new drift_schemas/ JSON snapshot;
//   (c) `dart run drift_dev make-migrations` -> generates the .steps.dart + a test scaffold;
//   (d) add ONE typed `from(n)To(n+1)` callback below.
// A SHIPPED migration is NEVER edited — a fix is a new higher schemaVersion that corrects
// forward (§4). Never select/update a not-yet-added column inside an older step.
// =====================================================================================

@DriftDatabase(
  tables: [
    // user (read-write)
    Profiles, Cards, LineBlocks, ReviewLog, ConfusionEdges, CycleConfigs, AppMeta,
    StudyNotes, // TODO: <- the new table, appended.
    // reference (read-only — never written at runtime, §2)
    Pages, Lines, Ayat, Surahs, Mushafs, MutashabihGroups, MutashabihMembers,
  ],
)
class HifzDatabase extends _$HifzDatabase {
  HifzDatabase(super.executor);

  // TODO: bump on every schema change; each bump needs a committed snapshot + a step.
  @override
  int get schemaVersion => 2; // was 1

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async => m.createAll(),
        onUpgrade: stepByStep(
          // ONE typed callback per version bump, generated against committed snapshots (§4).
          from1To2: (m, schema) async {
            // TODO: create exactly the new objects this version adds.
            await m.createTable(schema.studyNotes);
            // e.g. await m.addColumn(schema.card, schema.card.someNewColumn);
            // NEVER reference a column added in a LATER version here (§4 pitfalls).
          },
        ),
        // Pragmas are per-connection, NOT persisted — re-assert on every open (§1).
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON;');
        },
      );
}

// =====================================================================================
// 3. THE CONNECTION: WAL + synchronous=FULL + foreign_keys=ON, and the OPT-IN cipher guard
// -------------------------------------------------------------------------------------
// The mandatory floor (§3) is WAL crash-safety + transactional integrity. synchronous=FULL,
// not NORMAL, because a teacher sign-off must survive power loss (§3). Encryption is OPTIONAL,
// off by default (§5): the PRAGMA cipher; liveness guard refuses a silently-plaintext store.
// =====================================================================================

LazyDatabase openConnection({String? encryptionKeyHex}) {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'hifz.sqlite'));

    return NativeDatabase.createInBackground(
      file,
      // setup runs on the raw sqlite3 handle BEFORE drift touches the DB.
      setup: (raw) {
        // --- OPT-IN encryption (§5). Present only in the encryption-enabled flavor. ---
        if (encryptionKeyHex != null) {
          // Raw-key BLOB literal: full-entropy key, skips PBKDF2.
          raw.execute('PRAGMA key = "x\'$encryptionKeyHex\'";');
          // HARD GUARD: refuse to operate on a plaintext store that only LOOKS encrypted.
          if (raw.select('PRAGMA cipher;').isEmpty) {
            throw StateError(
              'Encryption build active but cipher is not live; refusing to open.',
            );
          }
        }
        // --- Mandatory crash-safety floor (§1, §3). ---
        raw.execute('PRAGMA journal_mode = WAL;'); // crash-safe append-only journal
        raw.execute('PRAGMA synchronous = FULL;'); // durable across power loss
        raw.execute('PRAGMA foreign_keys = ON;'); // SQLite leaves FKs OFF by default
        raw.execute('PRAGMA busy_timeout = 5000;'); // wait, don't throw, on brief contention
      },
    );
  });
}

// =====================================================================================
// 4. THE APPEND-ONLY DAO + THE commitReview SINGLE-TRANSACTION REPOSITORY BODY
// -------------------------------------------------------------------------------------
// review_log is APPEND-ONLY: this DAO exposes INSERT only — NO update/delete method, ever (§2).
// Every review is exactly ONE db.transaction; a review is several writes, all-or-nothing (§3).
// await EVERY query inside the transaction — a missing await runs after the tx closes => data
// loss (§3, the await footgun). The Future resolves only after the durable commit; the Riverpod
// controller (eng-create-riverpod-store) republishes AFTER — persist-before-publish.
// =====================================================================================

@DriftAccessor(tables: [ReviewLog, Cards, LineBlocks, ConfusionEdges])
class ReviewDao extends DatabaseAccessor<HifzDatabase> with _$ReviewDaoMixin {
  ReviewDao(super.db);

  /// Persist one review atomically. Returns only after the durable commit.
  ///
  /// `ReviewOutcome` is produced by the engine + grading pipeline
  /// (domain-scheduling-engine-rules, domain-grading-pipeline); this layer only persists it.
  Future<void> commitReview(ReviewOutcome r) {
    return db.transaction(() async {
      // 1. APPEND the immutable audit row (NEVER updated/deleted — the *sanad* record).
      await into(reviewLog).insert(r.logRow);

      // 2. UPDATE the card's engine state (D, S, due_at as a CalendarDate serial day, flags).
      await (update(cards)
            ..where((c) =>
                c.profileId.equals(r.profileId) & c.pageId.equals(r.pageId)))
          .write(r.cardUpdate);

      // 3. LAZILY create line-blocks for a repeatedly-lapsing page (if any).
      if (r.newLineBlocks.isNotEmpty) {
        await batch((b) => b.insertAll(lineBlocks, r.newLineBlocks));
      }

      // 4. BUMP mutashābihāt confusion edges (domain-mutashabihat-system), if a swap occurred.
      for (final edge in r.confusionBumps) {
        await into(confusionEdges).insertOnConflictUpdate(edge);
      }
      // Every query above is awaited; when this Future completes every row is durably on disk.
    });
    // TODO: do NOT add an UPDATE/DELETE method on review_log — append-only is enforced
    //       by the ABSENCE of those methods (§2). The only bulk touch is export / erase
    //       (domain-backup-format, PRD §16).
  }
}

// =====================================================================================
// 5. THE MIGRATION FIXTURE TEST (authored via eng-write-dart-test)
// -------------------------------------------------------------------------------------
// Lives in packages/data/test/, runs under `flutter test` (testing-strategy §1 unit tier,
// §8 `fast` job). Build a POPULATED v(n-1) DB, migrate, assert content SURVIVED and
// PRAGMA integrity_check == ok — this path touches every user's whole hifz history (§4).
// `drift_dev make-migrations` generates the SchemaVersion fixtures used below.
// =====================================================================================
//
// import 'package:drift/native.dart';
// import 'package:flutter_test/flutter_test.dart';
// import 'package:drift_dev/api/migrations.dart';
// import 'generated/schema.dart'; // produced by `drift_dev make-migrations`
//
// void main() {
//   late SchemaVerifier verifier;
//   setUpAll(() => verifier = SchemaVerifier(GeneratedHelper()));
//
//   test('v1 -> v2 preserves content and integrity_check is ok', () async {
//     // 1. Build a populated v(n-1) database.
//     final connection = await verifier.startAt(1);
//     final db = HifzDatabase(connection);
//     // TODO: seed representative rows — a profile, cards, and at least one review_log row
//     //       (the append-only audit trail is the highest-stakes content to preserve).
//
//     // 2. Migrate to current and let the verifier assert the schema matches the snapshot.
//     await verifier.migrateAndValidate(db, 2);
//
//     // 3. Assert CONTENT survived the upgrade.
//     // TODO: query the seeded review_log/card rows back and expect() them intact.
//
//     // 4. Assert the store is still structurally sound (§4 release-blocking).
//     final result = await db.customSelect('PRAGMA integrity_check;').get();
//     expect(result.single.data.values.first, 'ok');
//
//     // 5. If the encryption flavor is under test, also assert the cipher is still live (§5):
//     //    expect((await db.customSelect('PRAGMA cipher;').get()), isNotEmpty);
//
//     await db.close();
//   });
// }
