// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Mushaf extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Mushaf(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> mushafId = GeneratedColumn<String>(
      'mushaf_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> riwayah = GeneratedColumn<String>(
      'riwayah', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
      'name', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> lineCount = GeneratedColumn<int>(
      'line_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> pageCount = GeneratedColumn<int>(
      'page_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> fontFamily = GeneratedColumn<String>(
      'font_family', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> checksumSha256 = GeneratedColumn<String>(
      'checksum_sha256', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns => [
        mushafId,
        riwayah,
        name,
        lineCount,
        pageCount,
        fontFamily,
        checksumSha256
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mushaf';
  @override
  Set<GeneratedColumn> get $primaryKey => {mushafId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Mushaf createAlias(String alias) {
    return Mushaf(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const ['PRIMARY KEY(mushaf_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class Profile extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Profile(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
      'display_name', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> role = GeneratedColumn<String>(
      'role', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> locale = GeneratedColumn<String>(
      'locale', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> mushafId = GeneratedColumn<String>(
      'mushaf_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES mushaf(mushaf_id)');
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
      'created_at', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> settingsJson = GeneratedColumn<String>(
      'settings_json', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns =>
      [profileId, displayName, role, locale, mushafId, createdAt, settingsJson];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'profile';
  @override
  Set<GeneratedColumn> get $primaryKey => {profileId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Profile createAlias(String alias) {
    return Profile(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(profile_id)',
        'CHECK(role IN (\'self\', \'student\', \'child\'))',
        'CHECK(locale IN (\'ar\', \'fa\', \'ckb\'))'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class Surah extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Surah(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> surahId = GeneratedColumn<int>(
      'surah_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> nameAr = GeneratedColumn<String>(
      'name_ar', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> revelation = GeneratedColumn<String>(
      'revelation', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> ayahCount = GeneratedColumn<int>(
      'ayah_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> bismillahPre = GeneratedColumn<int>(
      'bismillah_pre', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL CHECK (bismillah_pre IN (0, 1))');
  @override
  List<GeneratedColumn> get $columns =>
      [surahId, nameAr, revelation, ayahCount, bismillahPre];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'surah';
  @override
  Set<GeneratedColumn> get $primaryKey => {surahId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Surah createAlias(String alias) {
    return Surah(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(surah_id)',
        'CHECK(surah_id BETWEEN 1 AND 114)',
        'CHECK(revelation IN (\'meccan\', \'medinan\'))',
        'CHECK(ayah_count > 0)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class Page extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Page(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> juz = GeneratedColumn<int>(
      'juz', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> hizb = GeneratedColumn<int>(
      'hizb', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> rub = GeneratedColumn<int>(
      'rub', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> surahStart = GeneratedColumn<int>(
      'surah_start', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
  late final GeneratedColumn<int> ayahStart = GeneratedColumn<int>(
      'ayah_start', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> surahEnd = GeneratedColumn<int>(
      'surah_end', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
  late final GeneratedColumn<int> ayahEnd = GeneratedColumn<int>(
      'ayah_end', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> lineCount = GeneratedColumn<int>(
      'line_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> qpcFontName = GeneratedColumn<String>(
      'qpc_font_name', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns => [
        pageId,
        juz,
        hizb,
        rub,
        surahStart,
        ayahStart,
        surahEnd,
        ayahEnd,
        lineCount,
        qpcFontName
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'page';
  @override
  Set<GeneratedColumn> get $primaryKey => {pageId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Page createAlias(String alias) {
    return Page(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(page_id)',
        'CHECK(page_id BETWEEN 1 AND 604)',
        'CHECK(juz BETWEEN 1 AND 30)',
        'CHECK(hizb BETWEEN 1 AND 60)',
        'CHECK(rub BETWEEN 1 AND 240)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class Card extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Card(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints:
          'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES page(page_id)');
  late final GeneratedColumn<String> track = GeneratedColumn<String>(
      'track', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<double> d = GeneratedColumn<double>(
      'd', aliasedName, false,
      type: DriftSqlType.double,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<double> s = GeneratedColumn<double>(
      's', aliasedName, false,
      type: DriftSqlType.double,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> lastReviewAt = GeneratedColumn<int>(
      'last_review_at', aliasedName, true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<int> dueAt = GeneratedColumn<int>(
      'due_at', aliasedName, true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<int> reps = GeneratedColumn<int>(
      'reps', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> lapses = GeneratedColumn<int>(
      'lapses', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> weakFlag = GeneratedColumn<int>(
      'weak_flag', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (weak_flag IN (0, 1))',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> signoffs = GeneratedColumn<int>(
      'signoffs', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> manualLock = GeneratedColumn<int>(
      'manual_lock', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (manual_lock IN (0, 1))',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> prayerCritical = GeneratedColumn<int>(
      'prayer_critical', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (prayer_critical IN (0, 1))',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> enabled = GeneratedColumn<int>(
      'enabled', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
      defaultValue: const CustomExpression('1'));
  @override
  List<GeneratedColumn> get $columns => [
        profileId,
        pageId,
        track,
        d,
        s,
        lastReviewAt,
        dueAt,
        reps,
        lapses,
        weakFlag,
        signoffs,
        manualLock,
        prayerCritical,
        enabled
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'card';
  @override
  Set<GeneratedColumn> get $primaryKey => {profileId, pageId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Card createAlias(String alias) {
    return Card(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(profile_id, page_id)',
        'CHECK(track IN (\'NEW\', \'NEAR\', \'FAR\', \'UNMEMORIZED\'))',
        'CHECK(d BETWEEN 1 AND 10)',
        'CHECK(s >= 0)',
        'CHECK(reps >= 0)',
        'CHECK(lapses >= 0)',
        'CHECK(signoffs >= 0)',
        'CHECK(track = \'UNMEMORIZED\' OR due_at IS NOT NULL)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class LineBlock extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  LineBlock(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> blockId = GeneratedColumn<String>(
      'block_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints:
          'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES page(page_id)');
  late final GeneratedColumn<int> lineStart = GeneratedColumn<int>(
      'line_start', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> lineEnd = GeneratedColumn<int>(
      'line_end', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> errorCount = GeneratedColumn<int>(
      'error_count', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  @override
  List<GeneratedColumn> get $columns =>
      [blockId, profileId, pageId, lineStart, lineEnd, errorCount];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'line_block';
  @override
  Set<GeneratedColumn> get $primaryKey => {blockId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  LineBlock createAlias(String alias) {
    return LineBlock(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(block_id)',
        'CHECK(line_start BETWEEN 1 AND 15)',
        'CHECK(line_end BETWEEN line_start AND 15)',
        'CHECK(error_count >= 0)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class ReviewLog extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ReviewLog(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> logId = GeneratedColumn<String>(
      'log_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints:
          'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES page(page_id)');
  late final GeneratedColumn<String> reviewedAt = GeneratedColumn<String>(
      'reviewed_at', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> trackAtReview = GeneratedColumn<String>(
      'track_at_review', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> grade = GeneratedColumn<String>(
      'grade', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> errorLinesJson = GeneratedColumn<String>(
      'error_lines_json', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<int> elapsedDays = GeneratedColumn<int>(
      'elapsed_days', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<double> rPredicted = GeneratedColumn<double>(
      'r_predicted', aliasedName, true,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<double> sBefore = GeneratedColumn<double>(
      's_before', aliasedName, true,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<double> sAfter = GeneratedColumn<double>(
      's_after', aliasedName, true,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<double> dBefore = GeneratedColumn<double>(
      'd_before', aliasedName, true,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<double> dAfter = GeneratedColumn<double>(
      'd_after', aliasedName, true,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<String> source = GeneratedColumn<String>(
      'source', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> teacherLabel = GeneratedColumn<String>(
      'teacher_label', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns => [
        logId,
        profileId,
        pageId,
        reviewedAt,
        trackAtReview,
        grade,
        errorLinesJson,
        elapsedDays,
        rPredicted,
        sBefore,
        sAfter,
        dBefore,
        dAfter,
        source,
        teacherLabel
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'review_log';
  @override
  Set<GeneratedColumn> get $primaryKey => {logId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ReviewLog createAlias(String alias) {
    return ReviewLog(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(log_id)',
        'CHECK(track_at_review IN (\'NEW\', \'NEAR\', \'FAR\', \'UNMEMORIZED\'))',
        'CHECK(grade IN (\'again\', \'hard\', \'good\', \'easy\'))',
        'CHECK(source IN (\'self\', \'teacher\'))'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class Ayah extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Ayah(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ayahId = GeneratedColumn<String>(
      'ayah_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> surah = GeneratedColumn<int>(
      'surah', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES surah(surah_id)');
  late final GeneratedColumn<int> ayah = GeneratedColumn<int>(
      'ayah', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES page(page_id)');
  late final GeneratedColumn<String> lineRefsJson = GeneratedColumn<String>(
      'line_refs_json', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> sajda = GeneratedColumn<int>(
      'sajda', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL CHECK (sajda IN (0, 1))');
  @override
  List<GeneratedColumn> get $columns =>
      [ayahId, surah, ayah, pageId, lineRefsJson, sajda];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'ayah';
  @override
  Set<GeneratedColumn> get $primaryKey => {ayahId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Ayah createAlias(String alias) {
    return Ayah(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const ['PRIMARY KEY(ayah_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class ConfusionEdge extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ConfusionEdge(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints:
          'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
  late final GeneratedColumn<String> ayahA = GeneratedColumn<String>(
      'ayah_a', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
  late final GeneratedColumn<String> ayahB = GeneratedColumn<String>(
      'ayah_b', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
  late final GeneratedColumn<double> weight = GeneratedColumn<double>(
      'weight', aliasedName, false,
      type: DriftSqlType.double,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0.0',
      defaultValue: const CustomExpression('0.0'));
  late final GeneratedColumn<String> lastConfusedAt = GeneratedColumn<String>(
      'last_confused_at', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns =>
      [profileId, ayahA, ayahB, weight, lastConfusedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'confusion_edge';
  @override
  Set<GeneratedColumn> get $primaryKey => {profileId, ayahA, ayahB};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ConfusionEdge createAlias(String alias) {
    return ConfusionEdge(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(profile_id, ayah_a, ayah_b)',
        'CHECK(ayah_a < ayah_b)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class CycleConfig extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  CycleConfig(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> profileId = GeneratedColumn<String>(
      'profile_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints:
          'NOT NULL REFERENCES profile(profile_id)ON DELETE CASCADE');
  late final GeneratedColumn<String> cycleType = GeneratedColumn<String>(
      'cycle_type', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> newLinesPerDay = GeneratedColumn<int>(
      'new_lines_per_day', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> nearWindowJuz = GeneratedColumn<int>(
      'near_window_juz', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> farTargetPerDay = GeneratedColumn<int>(
      'far_target_per_day', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> farCycleDays = GeneratedColumn<int>(
      'far_cycle_days', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> dailyBudgetMinutes = GeneratedColumn<int>(
      'daily_budget_minutes', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> pureCycleMode = GeneratedColumn<int>(
      'pure_cycle_mode', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (pure_cycle_mode IN (0, 1))',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<String> termLabelSet = GeneratedColumn<String>(
      'term_label_set', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> regionPreset = GeneratedColumn<String>(
      'region_preset', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns => [
        profileId,
        cycleType,
        newLinesPerDay,
        nearWindowJuz,
        farTargetPerDay,
        farCycleDays,
        dailyBudgetMinutes,
        pureCycleMode,
        termLabelSet,
        regionPreset
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'cycle_config';
  @override
  Set<GeneratedColumn> get $primaryKey => {profileId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  CycleConfig createAlias(String alias) {
    return CycleConfig(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(profile_id)',
        'CHECK(new_lines_per_day >= 0)',
        'CHECK(near_window_juz >= 0)',
        'CHECK(far_target_per_day >= 0)',
        'CHECK(far_cycle_days > 0)',
        'CHECK(daily_budget_minutes > 0)'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class AppMeta extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  AppMeta(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
      'key', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
      'value', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns => [key, value];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'app_meta';
  @override
  Set<GeneratedColumn> get $primaryKey => {key};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  AppMeta createAlias(String alias) {
    return AppMeta(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const ['PRIMARY KEY("key")'];
  @override
  bool get dontWriteConstraints => true;
}

class Line extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Line(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> lineId = GeneratedColumn<int>(
      'line_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> pageId = GeneratedColumn<int>(
      'page_id', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES page(page_id)');
  late final GeneratedColumn<int> lineNo = GeneratedColumn<int>(
      'line_no', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> lineType = GeneratedColumn<String>(
      'line_type', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> ayahRefsJson = GeneratedColumn<String>(
      'ayah_refs_json', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> textGlyphRef = GeneratedColumn<String>(
      'text_glyph_ref', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns =>
      [lineId, pageId, lineNo, lineType, ayahRefsJson, textGlyphRef];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'line';
  @override
  Set<GeneratedColumn> get $primaryKey => {lineId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Line createAlias(String alias) {
    return Line(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(line_id)',
        'CHECK(line_no BETWEEN 1 AND 15)',
        'CHECK(line_type IN (\'ayah\', \'surah_header\', \'basmala\'))'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class MutashabihGroup extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MutashabihGroup(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> groupId = GeneratedColumn<String>(
      'group_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> type = GeneratedColumn<String>(
      'type', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> noteKey = GeneratedColumn<String>(
      'note_key', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns => [groupId, type, noteKey];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mutashabih_group';
  @override
  Set<GeneratedColumn> get $primaryKey => {groupId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MutashabihGroup createAlias(String alias) {
    return MutashabihGroup(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
        'PRIMARY KEY(group_id)',
        'CHECK(type IN (\'identical\', \'near_identical\', \'structural\'))'
      ];
  @override
  bool get dontWriteConstraints => true;
}

class MutashabihMember extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MutashabihMember(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> groupId = GeneratedColumn<String>(
      'group_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES mutashabih_group(group_id)');
  late final GeneratedColumn<String> ayahId = GeneratedColumn<String>(
      'ayah_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES ayah(ayah_id)');
  late final GeneratedColumn<String> distinguishingWordIndexJson =
      GeneratedColumn<String>(
          'distinguishing_word_index_json', aliasedName, true,
          type: DriftSqlType.string,
          requiredDuringInsert: false,
          $customConstraints: 'NULL');
  @override
  List<GeneratedColumn> get $columns =>
      [groupId, ayahId, distinguishingWordIndexJson];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'mutashabih_member';
  @override
  Set<GeneratedColumn> get $primaryKey => {groupId, ayahId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MutashabihMember createAlias(String alias) {
    return MutashabihMember(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints =>
      const ['PRIMARY KEY(group_id, ayah_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final Mushaf mushaf = Mushaf(this);
  late final Profile profile = Profile(this);
  late final Surah surah = Surah(this);
  late final Page page = Page(this);
  late final Card card = Card(this);
  late final LineBlock lineBlock = LineBlock(this);
  late final ReviewLog reviewLog = ReviewLog(this);
  late final Ayah ayah = Ayah(this);
  late final ConfusionEdge confusionEdge = ConfusionEdge(this);
  late final CycleConfig cycleConfig = CycleConfig(this);
  late final AppMeta appMeta = AppMeta(this);
  late final Line line = Line(this);
  late final MutashabihGroup mutashabihGroup = MutashabihGroup(this);
  late final MutashabihMember mutashabihMember = MutashabihMember(this);
  late final Index cardDue = Index(
      'card_due', 'CREATE INDEX card_due ON card (profile_id, track, due_at)');
  late final Index lineBlockByCard = Index('line_block_by_card',
      'CREATE INDEX line_block_by_card ON line_block (profile_id, page_id)');
  late final Index reviewLogByCard = Index('review_log_by_card',
      'CREATE INDEX review_log_by_card ON review_log (profile_id, page_id, reviewed_at)');
  late final Index lineByPage = Index(
      'line_by_page', 'CREATE INDEX line_by_page ON line (page_id, line_no)');
  late final Index ayahByPage =
      Index('ayah_by_page', 'CREATE INDEX ayah_by_page ON ayah (page_id)');
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
        mushaf,
        profile,
        surah,
        page,
        card,
        lineBlock,
        reviewLog,
        ayah,
        confusionEdge,
        cycleConfig,
        appMeta,
        line,
        mutashabihGroup,
        mutashabihMember,
        cardDue,
        lineBlockByCard,
        reviewLogByCard,
        lineByPage,
        ayahByPage
      ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules(
        [
          WritePropagation(
            on: TableUpdateQuery.onTableName('profile',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('card', kind: UpdateKind.delete),
            ],
          ),
          WritePropagation(
            on: TableUpdateQuery.onTableName('profile',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('line_block', kind: UpdateKind.delete),
            ],
          ),
          WritePropagation(
            on: TableUpdateQuery.onTableName('profile',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('review_log', kind: UpdateKind.delete),
            ],
          ),
          WritePropagation(
            on: TableUpdateQuery.onTableName('profile',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('confusion_edge', kind: UpdateKind.delete),
            ],
          ),
          WritePropagation(
            on: TableUpdateQuery.onTableName('profile',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('cycle_config', kind: UpdateKind.delete),
            ],
          ),
        ],
      );
  @override
  int get schemaVersion => 1;
}
